### ISSUE TITLE
Boogie Wings

### ISSUE THREAD

**Issue by Ramon-Zarat** [leniad/dsp-emulator#37]
DSP V16 final Windows

1- Access violation in module dsp.exe
2- Two identical ROM set of different names must be present in the ROM folder: boogwing.zip and boogwins.zip, for the game to even try to load.

**Comment by leniad** [comment]
This is a WIP driver, right now it's just for testing purposes. Anyway, fixed Access violation and ZIP names.

**Comment by leniad** [comment]
Now works, but have many issues. Not in WIP.
