### ISSUE TITLE
Congo Bongo

### ISSUE THREAD

**Issue by Ramon-Zarat** [leniad/dsp-emulator#38]
DSP V16 final Windows

Won't load, access violation in module dsp.exe

**Comment by leniad** [comment]
If you run this driver without samples, you get Access violation. Fixed on next WIP release.

**Comment by Ramon-Zarat** [comment]
Tested and now working with samples. Thanks for the info! 

NOTE: Would it be possible to have a DAT file for the ROM and the samples so I could use clrmamepro to scan and clean the DSP sets? That would be great! :)
