### ISSUE TITLE
Are you OK?

### ISSUE THREAD

**Issue by dinkc64** [leniad/dsp-emulator#45]
Leniad, 
Hi, I'm dink from the FBAlpha (emu) project.
I like your project - pascal was my first favorite language. I have been following DSP for quite a while, but I noticed it's been a year or so since activity from you.  I hope you are alright! :)  Please let us know.  

best regards,
- dink

**Comment by leniad** [comment]
Hi dinkc64!
Thanks for asking! I’m fine, but my professional life has had a lot of changes these last two years, so I’ve had little time for the emulator.
As you know, sometimes life gets complicated and also with the pandemic (I live in Spain)... I’ve finally found stability and now I’m back for more code!

Leniad.

**Comment by azrael11** [comment]
That's good news to have you back leniad miss your updated Emulators.
Look at this i create a Frontend for emulators in Delphi -> https://www.youtube.com/watch?v=OkMp9gLOCRQ
Just think how good is to combine emulator and frontend.

Have a nice day and good code ;)

**Comment by dinkc64** [comment]
@leniad glad you're alright and can enjoy some coding again! :)

best regards,
- dink
