### ISSUE TITLE
dsp wont run on mac

### ISSUE THREAD

**Issue by patdiddy** [leniad/dsp-emulator#46]
when I tried running the newest version of DSP for Mac, I got the following message in terminal

"dyld: Library not loaded: /usr/local/lib/libSDL2_mixer-2.0.0.dylib
  Referenced from: ~/dsp_018b3.app/Contents/MacOS/dsp_lazarus
  Reason: image not found
zsh: abort      ~/dsp_018b3.app/Contents/MacOS/dsp_lazarus"

How do I fix that?

**Comment by leniad** [comment]
Hi!
You must have installed two libraries on Mac to run DSP.
SDL 2.0.X --> https://www.libsdl.org/release/SDL2-2.0.14.dmg
SDL mixer 2.0.X --> https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.4.dmg

Greetings.

**Comment by leniad** [comment]
I've tested v0.20 in Mac OS 12 and works fine with SDL 2 and SDL mixer 2
