### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by LeonisX** [leniad/dsp-emulator#48]
"If you want to add another language, edit any file with the extension '.lng' in the 'LNG' directory, rename it with the name of the language and send it to me to add it to the next version."

Where to find actual .lng file?

**Comment by LeonisX** [comment]
Okay, I understand, I will translate, let's say, an English language file. What is the next sequence of actions? Should I fork your project and pack the language file into this archive? Or I can also send by mail. How is it better?

UTF-8 encoding?

I also see that changing the language does not lead to the translation of absolutely all text in the emulator. Is this a temporary inconvenience that will be fixed in the future?

**Comment by leniad** [comment]
Take the English old lenguaje file, translate it to Russian, with the same lines order, and send back to me, I will add the translation the next DSP version.
UTF-8 is fine.
The languaje files are not ussed any more, are integrated in executable file.

Thanks in advance,
