### ISSUE TITLE
DSP 0.20 Final DAT has wrong size entries for sejyo

### ISSUE THREAD

**Issue by okurka** [leniad/dsp-emulator#51]
Rom size error in lines 2980, 2981 and 2982 in https://github.com/leniad/dsp-emulator/blob/master/src/misc/rom_export.pas

05k_15m.bin, 07k_17m.bin and 09k_19m.bin of senjyo should be $2000 in size, not $1000.

**Comment by leniad** [comment]
Fixed!
Thank you!
