### ISSUE TITLE
Fullscreen mode

### ISSUE THREAD

**Issue by azrael11** [leniad/dsp-emulator#52]
**Hello,**
Nice work. 

I have a problem when i switch to fullscreen mode .
The play area stuck in the  x=0, y=0 of the fullscreen window and not centered.

Am i doing something wrong?

Thank you

**Comment by leniad** [comment]
Hi!
Please download the latest version, I've done some modifications in full screen config.

**Comment by azrael11** [comment]
Ok now is better
