### ISSUE TITLE
Makefile

### ISSUE THREAD

**Issue by under4mhz** [leniad/dsp-emulator#53]
A makefile would make it much easier to build. I'm on Linux and I'd like to try it. Typically I would clone a github project and type "make" from the command line to build it.

Right now, I'd have to do some investigation to figure out how to compile it

**Comment by leniad** [comment]
Hi!
I'm sorry but lazarus option to create a make file, still don't work ("lazbuild --create-makefile").
You still can compile the emulator using command line, first install "lazarus", "fpc" and "fpc-source" packages, then go to "src/lazarus" directory and execute "lazbuild -B --cpu=x86_64 dsp.lpi"
