### ISSUE TITLE
Wrong ROM size of 88games in dat

### ISSUE THREAD

**Issue by okurka** [leniad/dsp-emulator#60]
Size of 861a04.a and 861a04.c in 88games is wrong in the exported DAT.

Real size is $10000 instead of $8000 for both roms.

https://github.com/leniad/dsp-emulator/blob/cbe42fa327ca90266dd039070533961fd9058406/src/misc/rom_export.pas#L3441
https://github.com/leniad/dsp-emulator/blob/cbe42fa327ca90266dd039070533961fd9058406/src/misc/rom_export.pas#L3442

**Comment by leniad** [comment]
Fixed, changed in the new WIP release.
Thank you!
