### ISSUE TITLE
Full Screen on  0.23WIP1

### ISSUE THREAD

**Issue by veb-xenon** [leniad/dsp-emulator#61]
First of all, thanks for your emulator! For now, the best for playing Super Cassette Vision games. And it's great to have more multiemulators there.

What I've found is that I'm unable to play the games in full screen. When I select full screen, game is displayed at the left corner on the screen and it's not centered nor with the correct aspect ratio. So finally I always play for now in window mode.

I'll put you screenshots later when I'm on the computer :-)

**Comment by veb-xenon** [comment]
Here you can find the screenshots. I'm using Windows 11 23H2.

![imagen](https://github.com/user-attachments/assets/2371c33f-0571-495d-a916-c888b5514d37)
![imagen](https://github.com/user-attachments/assets/151bf25c-3750-4f0d-83f9-bf1972c81846)
![imagen](https://github.com/user-attachments/assets/2b832b0f-7507-4ba6-b2ea-341e692c9935)

**Comment by leniad** [comment]
Hi!
Today I will release a new WIP version, that includes a rewrite of the full screen section.
After a loooong journey, I think it's finally solved!
**Before**
![after](https://github.com/user-attachments/assets/09014a03-b459-43b6-8812-9ee946f4d5ae)

**0.23WIP2**
![023wip2](https://github.com/user-attachments/assets/c4838bbd-9a83-4109-9097-4c8c8a6ef4e7)

Thank you!

**Comment by veb-xenon** [comment]
Thanks very much! 😊
